
services:
  # --- クライアント側 ---
  client1:
    image: cefuntu-all
    container_name: c1-nonoichi
    hostname: c1-nonoichi
    environment:
      - NODE_TYPE=client
    cap_add:
      - "NET_ADMIN"
      - SYS_ADMIN
    privileged: true
    tty: true
    networks:
      cefore_network:
        ipv4_address: 172.18.0.1 # 固定IP
    volumes:
      - type: bind
        source: ./docker
        target: /docker
    entrypoint: /docker/init_cefnetd.sh

  client2:
    image: cefuntu-all
    container_name: c2-nonoichi
    hostname: c2-nonoichi
    environment:
      - NODE_TYPE=client
    cap_add:
      - "NET_ADMIN"
      - SYS_ADMIN
    privileged: true
    tty: true
    networks:
      cefore_network:
        ipv4_address: 172.18.0.2 # 固定IP
    volumes:
      - type: bind
        source: ./docker
        target: /docker
    entrypoint: /docker/init_cefnetd.sh

# --- サーバー側 ---
  server:
    image: cefore/cefore
    container_name: server
    cap_add: [ "NET_ADMIN" ]
    tty: true
    networks:
      cefore_network:
        ipv4_address: 172.18.0.30 # 固定IP
    volumes:
      - ./config/server_setup.sh:/root/setup.sh
    entrypoint: /root/setup.sh

  # --- ルータ群 ---
  r1-nonoichi:
    image: cefuntu-all
    container_name: r1-nonoichi
    hostname: r1-nonoichi
    environment:
      - NODE_TYPE=router
    cap_add:
      - "NET_ADMIN"
      - SYS_ADMIN
    privileged: true
    tty: true
    networks:
      cefore_network:
        ipv4_address: 172.18.0.11 # 固定IP
    volumes:
      - type: bind
        source: ./docker
        target: /docker
    entrypoint: /docker/init_cefnetd.sh
  
   r2-tokyo:
    image: cefuntu-all
    container_name: r2-tokyo
    hostname: r2-tokyo
    environment:
      - NODE_TYPE=router
    cap_add:
      - "NET_ADMIN"
      - SYS_ADMIN
    privileged: true
    tty: true
    networks:
      cefore_network:
        ipv4_address: 172.18.0.50 # 固定IP
    volumes:
      - type: bind
        source: ./docker
        target: /docker
    entrypoint: /docker/init_cefnetd.sh

   r3-nagoya:
    image: cefuntu-all
    container_name: r3-nagoya
    hostname: r3-nagoya
    environment:
      - NODE_TYPE=router
    cap_add:
      - "NET_ADMIN"
      - SYS_ADMIN
    privileged: true
    tty: true
    networks:
      cefore_network:
        ipv4_address: 172.18.0.51 # 固定IP
    volumes:
      - type: bind
        source: ./docker
        target: /docker
    entrypoint: /docker/init_cefnetd.sh

   r4-osaka:
    image: cefuntu-all
    container_name: r4-osaka
    hostname: r4-osaka
    environment:
      - NODE_TYPE=router
    cap_add:
      - "NET_ADMIN"
      - SYS_ADMIN
    privileged: true
    tty: true
    networks:
      cefore_network:
        ipv4_address: 172.18.0.52 # 固定IP
    volumes:
      - type: bind
        source: ./docker
        target: /docker
    entrypoint: /docker/init_cefnetd.sh

   r5-sendai:
    image: cefuntu-all
    container_name: r5-sendai
    hostname: r5-sendai
    environment:
      - NODE_TYPE=router
    cap_add:
      - "NET_ADMIN"
      - SYS_ADMIN
    privileged: true
    tty: true
    networks:
      cefore_network:
        ipv4_address: 172.18.0.53 # 固定IP
    volumes:
      - type: bind
        source: ./docker
        target: /docker
    entrypoint: /docker/init_cefnetd.sh

   r6-ishikawa:
    image: cefuntu-all
    container_name: r6-ishikawa
    hostname: r6-ishikawa
    environment:
      - NODE_TYPE=router
    cap_add:
      - "NET_ADMIN"
      - SYS_ADMIN
    privileged: true
    tty: true
    networks:
      cefore_network:
        ipv4_address: 172.18.0.54 # 固定IP
    volumes:
      - type: bind
        source: ./docker
        target: /docker
    entrypoint: /docker/init_cefnetd.sh

networks:
  cefore_network:
    external: true # "cefore_network"という名前の既存ネットワークを単に"利用する"  docker network create --driver=bridge --subnet=172.19.0.0/24 cefore_network
    driver: bridge          # <-- (A) L2の定義
    ipam:
      config:
        - subnet: 172.18.0.0/24 # <-- (B) L3の定義

