# Dockerfile_debian_slim
# docker build -t cefbian:test .

FROM linuxcontainers/debian-slim:latest
LABEL description="Cefore v0.11.0 on Debian Slim"

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt -y upgrade
RUN apt update --fix-missing
RUN apt install -y --no-install-recommends \
    sudo \
    libssl-dev \
    make \
    cmake \
    automake \
    build-essential \
    procps \
    unzip \
    python3-pip \
    python3-venv \
    python3-dev
#RUN rm -rf /var/lib/apt/lists/*

# Dockerのボリューム機能でホストのファイルをコンテナにマウントした際のパーミッション問題を防ぐ
ARG USER_ID=1000
ARG GROUP_ID=1000
# コンテナ内でコマンドを実行するための、rootではない一般ユーザー dockeruser を作成
# -m: ホームディレクトリを作成, -s /bin/bash: ログインシェルを /bin/bash に設定
RUN groupadd -g ${GROUP_ID} dockeruser && useradd -u ${USER_ID} -g ${GROUP_ID} -m -s /bin/bash dockeruser -p user

RUN mkdir -p /docker

WORKDIR /tmp
COPY v0.11.0.zip cefpyco-master.zip .
RUN unzip v0.11.0.zip -d .
RUN unzip cefpyco-master.zip -d .
#RUN unzip cefbabel.zip -d .

# Build
## Cefore
WORKDIR cefore-0.11.0
ENV CEFORE_DIR=/usr/local
RUN aclocal
RUN automake && \
    ./configure --enable-csmgr --enable-cache && \
    make && \
    make install && \
    ldconfig

## Cefpyco
WORKDIR /tmp
#unzip master.zip -d .
RUN python3 -m venv venvcef
#RUN . venvcef/bin/activate
RUN venvcef/bin/pip3 install --upgrade pip build setuptools && \
    venvcef/bin/pip3 install wheel numpy click rich pytest pytest-sugar
WORKDIR /tmp/cefpyco-master
RUN echo `ls` >> /docker/ls.txt
RUN cmake . #-DPYTHON_EXECUTABLE=/tmp/venvcef/bin/python3
RUN sed -i 's|execute_process(COMMAND /usr/bin/python3 -m build|execute_process(COMMAND /tmp/venvcef/bin/python3 -m build|g' cmake_install.cmake
RUN sed -i 's|execute_process(COMMAND /usr/bin/python3 -m pip install|execute_process(COMMAND /tmp/venvcef/bin/python3 -m pip install|g' cmake_install.cmake
RUN make
RUN make install && \
    ldconfig
# sudo /home/{User Name}/venvcef/bin/pip {python cefapp}

## Cefbabel
WORKDIR /tmp
COPY cefbabel.zip .
RUN unzip cefbabel.zip -d .
WORKDIR /tmp/cefbabel-main
RUN make && make install  && ldconfig

# App tools
#pip install opencv-python numpy pandas
#apt update --fix-missing
#apt -y install libopencv-dev --fix-missing

RUN rm -rf /tmp/* 
RUN apt purge -y make cmake automake build-essential unzip wget network-manager && \
    apt autoremove -y && \
    rm -r /var/lib/apt/lists/*

# ./debian/
#COPY ./
# Bash Utils
#COPY ./bash /app
#COPY entrypoint.sh /usr/local/bin/entrypoint.sh
#RUN chmod +x /usr/local/bin/entrypoint.sh
# コンテナ起動時に実行されるエントリーポインaト !!!
#ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
ENTRYPOINT ["/docker/bash/cefore_ep.sh"]
