# Dockerfile_debian_slim
# docker build -t cefbian:test .

FROM linuxcontainers/debian-slim:latest
LABEL description="Cefore v0.11.0 on Debian Slim"

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update --fix-missing && apt -y upgrade
#RUN apt update --fix-missing
RUN apt install -y --no-install-recommends \
    sudo \
    libssl-dev \
    make \
    automake \
    build-essential \
    procps \
    #zip \
    unzip \
    python3-pip \
    python3-venv
#RUN rm -rf /var/lib/apt/lists/*

# Dockerのボリューム機能でホストのファイルをコンテナにマウントした際のパーミッション問題を防ぐ
ARG USER_ID=1000
ARG GROUP_ID=1000
# コンテナ内でコマンドを実行するための、rootではない一般ユーザー dockeruser を作成
# -m: ホームディレクトリを作成, -s /bin/bash: ログインシェルを /bin/bash に設定
RUN groupadd -g ${GROUP_ID} dockeruser && useradd -u ${USER_ID} -g ${GROUP_ID} -m -s /bin/bash dockeruser
RUN mkdir -p /docker/workdir
#RUN echo `ls -l /docker/workdir` >> /docker/ll.txt
RUN chown ${USER_ID}:${GROUP_ID} /docker/workdir
#RUN echo `ls -l /docker/workdir` >> /docker/ll2.txt

WORKDIR /tmp
#RUN cp -r /docker/cefore/v0.11.0.zip .
COPY v0.11.0.zip cefpyco-master.zip .
RUN unzip v0.11.0.zip -d .
RUN unzip cefpyco-master.zip -d .
# Build
## Cefore
WORKDIR cefore-0.11.0
ENV CEFORE_DIR=/usr/local
RUN aclocal
RUN automake && \
    ./configure --enable-csmgr --enable-cache && \
    make && \
    make install && \
    ldconfig
## Cefpyco
WORKDIR /tmp
#RUN apt update --fix-missing && apt install -y python3-dev wget
RUN apt install cmake python3-dev -y
#wget https://github.com/cefore/cefpyco/archive/refs/heads/master.zip
#unzip master.zip -d .
RUN python3 -m venv venvcef
RUN . venvcef/bin/activate && \
    pip3 install --upgrade build && \
    pip3 install numpy click rich pytest pytest-sugar && \
    cd cefpyco-master && \
    cmake . && \
    make && \
    make install

# App tools
#pip install opencv-python numpy pandas
#apt update --fix-missing
#apt -y install libopencv-dev --fix-missing

#RUN rm -rf /tmp/*

# ./debian/
#COPY ./
# Bash Utils
#COPY ./bash /app
#COPY entrypoint.sh /usr/local/bin/entrypoint.sh
#RUN chmod +x /usr/local/bin/entrypoint.sh
# コンテナ起動時に実行されるエントリーポインaト !!!
#ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
ENTRYPOINT ["/docker/bash/cefore_ep.sh"]
