# Dockerfile_producer debian_slim
# docker build -t cefbian:test .

FROM linuxcontainers/debian-slim:latest
LABEL description="Cefore Producer on Debian Slim"

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt -y upgrade
#RUN apt update --fix-missing
RUN apt install -y --no-install-recommends \
    sudo \
    libssl-dev \
    make \
    automake \
    build-essential \
    procps \
    #zip \
    unzip
#RUN rm -rf /var/lib/apt/lists/*

ARG USER_ID=1000
ARG GROUP_ID=1000
RUN groupadd -g ${GROUP_ID} dockeruser && useradd -u ${USER_ID} -g ${GROUP_ID} -m -s /bin/bash dockeruser
RUN mkdir -p /docker/workdir
RUN chown ${USER_ID}:${GROUP_ID} /docker/workdir

WORKDIR /tmp
#RUN cp -r /docker/cefore/v0.11.0.zip .
COPY v0.11.0.zip .
COPY cefpyco-master.zip .
RUN unzip v0.11.0.zip -d .
RUN mv cefore-0.11.0 cefore

WORKDIR cefore


ENV CEFORE_DIR=/usr/local
RUN aclocal
RUN automake && \
    ./configure --enable-csmgr --enable-cache && \
    make && \
    make install && \
    ldconfig

#RUN rm -rf /tmp/*


COPY ./
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

# コンテナ起動時に実行されるエントリーポイント
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

# cefpyco
apt update
apt install -y cmake python3-pip python3-dev python3-venv wget unzip
cd tmp
#wget https://github.com/cefore/cefpyco/archive/refs/heads/master.zip
#unzip master.zip -d .
unzip /app

python3 -m vnev venvcef
. venvcef/bin/activate
pip3 install --upgrade build
pip3 install numpy click rich pytest pytest-sugar
cd cefpyco-master
cmake .
make
make install

# App tools
#pip install opencv-python numpy pandas
#apt update --fix-missing
#apt -y install libopencv-dev --fix-missing

